### PR TITLE
Socket configuration

### LINKED ISSUE #3977: Configure sockets passed through systemd socket activation
When the diffusion is creating sockets we set the following options:

* `SO_REUSEADDR 1`
* `SO_REUSEPORT 1`
* `TCP_NODELAY 1`
* `IPV6_V6ONLY 1` _only for ipv6 addresses_
* `SO_LINGER 1 0`

The following tables shows which options are supported by systemd socket
activation:

socket option  | socket activation
---------------|------------------
`SO_REUSEADDR` | -
`SO_REUSEPORT` | `ReusePort=`
`TCP_NODELAY`  | `NoDelay=`
`IPV6_V6ONLY`  | `BindIPv6ONLY=`
`SO_LINGER`    | -

### PR DESCRIPTION
**Pull request by coot**
# Description

Fixes #3977
         
- Updated network dependency (haskell/network#491 was merged)  
- snocket: various stylistic changes       
- snocket: do not configure sockets in bind method 
- connection-manager: add a method to configure connection sockets 
- socket: added methods to configure sockets 
- Increment zfs copy fail counter
     

# Checklist

- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Commits have useful messages
    - [ ] New tests are added if needed and existing tests are updated
    - [ ] If this branch changes Consensus and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../ouroboros-consensus/docs/interface-CHANGELOG.md)
    - [ ] If this branch changes Network and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../docs/interface-CHANGELOG.md)
    - [ ] If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.
- Pull Request
    - [ ] Self-reviewed the diff
    - [x] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [x] Reviewer requested

### CODE REVIEW

**Review by bolt12 — APPROVED** [review]
LGTM!

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
There is a strange windows test failure:

configuration | bind | getSocketName | error
--------------|------|---------------|------
yes | yes | yes | `getSocketName: failed (Invalid argument (WSAEINVAL))` _unexpected_
no  | yes | yes | `bind: failed (Address already in use (WSAEADDRINUSE))` _expected_
yes | no  | yes | _no error_  
yes | yes | no  | `bind: failed (Address already in use (WSAEACCESS))` _unexpected_

`configuration` options: `ReuseAddr`, `NoDelay`, `Linger`; Sequence: `configuration -> bind -> getSocketName`.

**Comment by coot** [comment]
bors merge

**Pull request merged**
