### PR TITLE
nix: add slow-RealTPraos to nightly-checks in default.nix

### LINKED ISSUE #2393: Relegate additional and longer ThreadNet tests to a nightly run
Currently, the motivation is to consistently reach later epochs during Shelley eras.

Issues #1047 and #1102 are somewhat similar.

### PR DESCRIPTION
**Pull request by nfrisby**
Fixes #2393.

### CODE REVIEW

**Comment by nfrisby** [comment]
This is progress towards Issue #2393

**Comment by nfrisby** [comment]
I've requested review again because I've made this nightly test less trivial than it original was on this PR: it actually runs 100 RealTPraos tests (for 10 to 15 minutes or so), while the per-push behavior is to just run 20 since they are slow.

I plan to follow-up with changes that it run even more tests and also longer tests during this nightly build, but that will be a subsequent PR.

I've invoked this branch via BuildKite in order to demonstrate -- see the result at https://buildkite.com/input-output-hk/ouroboros-network-nightly/builds/137

P.S. - Sorry for all the noisy updates above -- I forget this PR was showing all of my debugging pushes. Locales are too hard :(

**Comment by nfrisby** [comment]
The "â‰ˆ" seen in the log file if you click it in the artifact list is Not My Fault :)

https://github.com/input-output-hk/ouroboros-network/blob/df6752abeb592776c10079f7ea67e3e4feeef6c0/.buildkite/slow-RealTPraos.sh#L31-L34

Once your browser is showing the text file, you should be able to find a "Text Encoding" option or somewhere similar that you can override to Unicode. That'll fix it. Or you can download and view in an editor eg.

**Comment by nfrisby** [comment]
Just an update. Since I'm in elbow deep here already, I'm going ahead and including other tests suites and running thousands of tests as part of this PR. The subsequent PR will make each individual test more aggressive (eg run for multiple epochs/more slots).

My latests WIP script runs 1000 RealTPraos and 1000 Cardano tests per physical core. I'm estimating 2-3 hours. It's queued up here https://buildkite.com/input-output-hk/ouroboros-network-nightly/builds/150 but I haven't pushed the commits to this PR's branch yet, since it's not quite ready yet.

**Comment by nfrisby** [comment]
I think this is a final candidate: https://buildkite.com/input-output-hk/ouroboros-network-nightly/builds/152

If that goes smoothly, I'll push its commits to this PR.

**Comment by mrBliss** [comment]
Ha:

> Academic tradition requires you to cite works you base your article on.
> If you use programs that use GNU Parallel to process data for an article in a
> scientific publication, please cite:
>
>   O. Tange (2018): GNU Parallel 2018, Mar 2018, ISBN 9781387509881,
>   DOI https://doi.org/10.5281/zenodo.1146014
>
> This helps funding further development; AND IT WON'T COST YOU A CENT.
> If you pay 10000 EUR you should feel free to use GNU Parallel without citing.
>
> More about funding GNU Parallel and the citation notice:
> https://www.gnu.org/software/parallel/parallel_design.html#Citation-notice
>
> To silence this citation notice: run 'parallel --citation' once.

Maybe include a call to `parallel --citation` first or `touch ~/.parallel/will-cite`.

**Comment by nfrisby** [comment]
OK, last review request on this PR, I promise :)

The script is now running thousands of RealTPraos and Cardano tests. The RealTPraos depend on the `--iohk-enable-nightly-tests` flag in a relatively trivial way, and the Cardano tests don't at all. I'm now preparing a follow-up PR that causes the Cardano tests to run for more slots when the flag is set (this requires some changes to the KES config etc -- relegated to separate PR.)

It runs locally and also on the BuildKite instance. When I injected failures, those also end up in the log artifacts (I had a `'` vs `"` bug in the bash, at first). I think it's at least robust enough for this initial merge.

It's more `bash` than I'd like, but I think it's rather extensible as-is, at least. I'll open a tech-debt ticket to consider alternatives. GNU parallel at least certainly has a good power-to-weight ratio.

**Comment by nfrisby** [comment]
> LGTM. I'm no bash expert (judging by the amount of bash code in `cardano-node`, there are a few there 😁) so I'm trusting you.

Want to summon one of them?

> When looking at the test jobs on BuildKite: is it intentional that you don't see the progress of the job (no output) while running? I suppose so, because parallel output would be quite confusing. I'm guessing that the output for finished runs is shown progressively?

Since I'm running tens of tests, I decided to relegate test output to artifacts. This does mean there will be no increment results indicating progress. Is that a show-stopper?

GNU parallel does offer progress indicators. Do any of these look appropriate? In particular, would the relevant `<backspace>`/`<carriage return>` be appropriate for BuildKite stdout? https://www.gnu.org/software/parallel/parallel_tutorial.html#Progress-information

> The artifacts of the last finished (failed) test (at the time of writing this), i.e., "Frisby big test 4", are empty. Is that the bash bug you mention?

Yep; fixed now.

**Comment by mrBliss** [comment]
> > LGTM. I'm no bash expert (judging by the amount of bash code in `cardano-node`, there are a few there grin) so I'm trusting you.
> 
> Want to summon one of them?

No, that's not necessary :slightly_smiling_face: 
> 
> > When looking at the test jobs on BuildKite: is it intentional that you don't see the progress of the job (no output) while running? I suppose so, because parallel output would be quite confusing. I'm guessing that the output for finished runs is shown progressively?
> 
> Since I'm running tens of tests, I decided to relegate test output to artifacts. This does mean there will be no incremental results indicating progress. Is that a show-stopper?

I think not, as it's a nightly job anyway.

> 
> GNU parallel does offer progress indicators. Do any of these look appropriate? In particular, would the relevant `<backspace>`/`<carriage return>` characters be appropriate for BuildKite stdout? https://www.gnu.org/software/parallel/parallel_tutorial.html#Progress-information

I think it's fine. If we ever have the need for progress indicators, we can think about it.

> > The artifacts of the last finished (failed) test (at the time of writing this), i.e., "Frisby big test 4", are empty. Is that the bash bug you mention?
> 
> Yep; fixed now.

:+1:

**Comment by nfrisby** [comment]
bors merge

**Pull request merged**
