### PR TITLE
Add some micro- benchmarks for PeerMetrics

### LINKED ISSUE #3832: Integrate space and execution time measurments in some of the tests
Integrate space and execution time measurements (on individual tests or test-groups), from these measurements one might detect

* a time or space eﬀiciency regression.
* a space leak

E.g., given a single test, but run on a longer ”timeframe”, does this use more memory?

### PR DESCRIPTION
**Pull request by mtullsen**
# Description

This resolves #3832.

The goals of this PR are to
 - Create one time/space benchmark (as a paradigm for other benchmarks to follow).
 - Adapt the the PeerMetric testing code into an efficient benchmark that we can use for both time & space measurements of the PeerMetric code.

One can run the benchmark thus
```
cabal bench sim-benchmarks
cabal bench --benchmark-options '+RTS -T' sim-benchmarks
  # this adds space profiling
```

# Checklist

- Branch
    - [x] Updated changelog files.
    - [x] Commit sequence broadly makes sense
    - [x] Commits have useful messages
    - [x] The documentation has been properly updated
    - [x] New tests are added if needed and existing tests are updated
    - [x] If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.
- Pull Request
    - [x] Self-reviewed the diff
    - [x] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [x] Reviewer requested

### CODE REVIEW

**Review by coot — APPROVED** [review]
LGTM

**Comment by coot** [comment]
There's a build failure: https://github.com/input-output-hk/ouroboros-network/actions/runs/6212332000/job/17104416622; It seems wrong version of `tasty` is required.  I added `emptyProgress` to `tasty-1.5`.

**Review by disassembler — APPROVED** [review]

**Comment by mtullsen** [comment]
@coot : with the last commit, c7bb57081545ca8f216edc6b6f37997736700a3f , the only failures I'm seeing are timeouts and various "un-understandable to me" nix failures.  Any guidance here? Thanks.

**Comment by coot** [comment]
@mtullsen I rebased the PR, and added a few benign commits on top.

**Pull request merged**
