### PR TITLE
Add Javier Sagredo to consensus-team onboarding document

### PR DESCRIPTION
**Pull request by Jasagredo**
Adding myself to the consensus team document.

### CODE REVIEW

**Review by nfrisby — APPROVED** [review]
Approved. Welcome!

**Review by EncodePanda — APPROVED** [review]
welcome :)

**Comment by drathier** [comment]
Hope you'll like it there, I'll miss working with you!

**Review by dcoutts — APPROVED** [review]

**Comment by dcoutts** [comment]
bors merge

**Comment by nfrisby** [comment]
@Jasagredo We fixed up the `bors` config, and we think the `bors` command will work the next time you issue it 👍

**Pull request merged**
