### PR TITLE
remove tullia

### PR DESCRIPTION
**Pull request by dermetfan**
# Description

Remove tullia/cicero jobs as we are going to use Hydra instead. Hydra jobs are already in place and we can start using them without any changes.

# Checklist

- Branch
    - ~~Updated changelog files.~~
    - [x] Commit sequence broadly makes sense
    - [x] Commits have useful messages
    - ~~The documentation has been properly updated~~
    - ~~New tests are added if needed and existing tests are updated~~
    - ~~If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.~~
- Pull Request
    - [x] Self-reviewed the diff
    - [x] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - ~~How does this affect downstream repositories and/or end-users?~~
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [x] Reviewer requested

### CODE REVIEW

**Comment by coot** [comment]
So now these jobs should be marked as required:

* `ci/hydra-build:aarch64-darwin.required`
* `ci/hydra-build:x86_64-darwin.required`
* `ci/hydra-build:x86_64-linux.required`

instead of `ci` and `ci (x86_64-linux)`, right?

**Comment by coot** [comment]
When I follow the link to detail, e.g. [ci/hydra-build:x86_64-linux.required](https://ci.iog.io/build/33653), the log there is empty.

Also there are some failures in the [ci/eval](https://ci.iog.io/eval/519#tabs-errors).

**Comment by dermetfan** [comment]
> So now these jobs should be marked as required:

Yes.

> there are some failures in the [ci/eval](https://ci.iog.io/eval/519#tabs-errors)

They are just saying that Hydra could not evaluate the jobs for aarch64-linux (we have no builder for that yet). We could remove aarch64-linux from the supported systems to get rid of them but they can simply be ignored.

> the log there is empty

`required` is just an aggregation of other jobs. You need to click the ["constituents" tab](https://ci.iog.io/build/33651#tabs-constituents) to see them.

**Review by coot — APPROVED** [review]
LGTM

**Pull request merged**
