### PR TITLE
WIP: Implement permissive BFT

### LINKED ISSUE #168: Implement permissive BFT
Per discussion with @edsko, I'll implement an instance of the `Ouroboros.Consensus.Protocol.Abstract.OuroborosTag` class for the permissive BFT protocol.

### PR DESCRIPTION
**Pull request by mdimjasevic**
This PR implements the integration of the `cs-blockchain` package from the `cardano-chain` repository into `ouroboros-consensus`. In particular, it implements the `OuroborosTag` class from the `Ouroboros.Consensus.Protocol.Abstract` module for the permissive BFT blockchain protocol.

Closes #168.

Remark 1: I pulled from @avieth's branch that gets this repository building with GHC 8.6.3, but I guess it still hasn't made its way into `master`. 
Remark 2: Once done and approved, I'll squash commits to clean up the commit noise.

### CODE REVIEW

**Comment by edsko** [comment]
Depends on https://github.com/input-output-hk/ouroboros-network/pull/183 .

**Comment by mdimjasevic** [comment]
@edsko, does what I have now (see https://github.com/input-output-hk/ouroboros-network/pull/204/files#diff-5446ac1cb2f5224910f2de1c9450b4a7) achieve what you had in mind with a polymorphic block type? If it makes it easier for you, check the last commit only, which is short: commit 18420ec6cdfc495553c425ee256c3ba4cfc70256.

**Comment by edsko** [comment]
Yup, looks good!

**Comment by nc6** [comment]
Closing this branch, it's not being worked on

**Pull request closed without merging**
