### PR TITLE
Cosmetic changes to the `ouroboros-consensus` codebase

### PR DESCRIPTION
**Pull request by Jasagredo**
# Description

- `cabal-fmt` on cabal files
- `stylish-haskell` now puts all the imports in one group
- `HFC.Utils.*` and some `Ou.Consensus.Utils` modules have been moved to `Data.SOP`

Supersedes #4451 #4443 #4440 and #4431

### CODE REVIEW

**Review by amesgen — APPROVED** [review]
Let's hope that darwin CI passes after sufficiently many restarts :crying_cat_face:

**Comment by dnadales** [comment]
We should also https://github.com/input-output-hk/ouroboros-consensus/issues/16

**Pull request merged**
