### PR TITLE
Update to latest cardano-ledger-specs

### PR DESCRIPTION
**Pull request by nc6**
This PR pulls in changes to the stake aggregation computation to allow it to be computed incrementally. This will result in the ledger state needing to be rebuilt.

### CODE REVIEW

**Review by dnadales — APPROVED** [review]

**Comment by nc6** [comment]
bors merge

**Review by EncodePanda — APPROVED** [review]
I think I'm too late because bors is already running. I was just about to add that those two commits should have been squashed before merging, because we want to limit number of failing commits. Other then that LGTM

**Comment by nc6** [comment]
I can squash

**Comment by nc6** [comment]
bors merge

**Pull request merged**
