### PR TITLE
Use `Data.ByteString.Char8.putStr` in MonadSay IO Instance

### PR DESCRIPTION
**Pull request by coot**
MonadSay should be removed in favour of iohk-monitoring-framework.

### CODE REVIEW

**Comment by coot** [comment]
@karknu I don't see `Say` package in the [cabal file](https://github.com/input-output-hk/ouroboros-network/blob/coot/monad-say/io-sim/io-sim.cabal).

**Comment by karknu** [comment]
It is in `ouroboros-network.cabal`.

**Comment by coot** [comment]
@karknu Done

**Pull request merged**
