### PR TITLE
consensus: draft the sketch implementation plan for Ouroboros Genesis

### PR DESCRIPTION
**Pull request by nfrisby**
Recording the design sketch @edsko and I developed recently. This will guide the implementation effort. We're not sure when that will happen; we are choosing to assess the UTxO HD work impact/parallelizability/etc first.

### CODE REVIEW

**Review by edsko — APPROVED** [review]
These are the results of long and hard discussions over meet.

**Comment by nfrisby** [comment]
@dcoutts Would you like to review this over a phone call?

**Comment by nfrisby** [comment]
I rebased on to `origin/master`.

**Pull request merged**
