### PR TITLE
Update dependency on cardano-ledger-specs

### PR DESCRIPTION
**Pull request by mrBliss**

### CODE REVIEW

**Comment by mrBliss** [comment]
bors merge

**Comment by mrBliss** [comment]
bors merge

**Comment by mrBliss** [comment]
@nfrisby This doesn't bring in the latest changes to `ConcreteCrypto`, I'll leave that to you :slightly_smiling_face:

**Comment by nfrisby** [comment]
> @nfrisby This doesn't bring in the latest changes to `ConcreteCrypto`, I'll leave that to you 🙂

I just opened PR #2490 for that, FYI.

**Pull request merged**
