### PR TITLE
network: refactor with Map.intersectionWith in Handshake server

### PR DESCRIPTION
**Pull request by nfrisby**
The code was using `List.intersect` to cope with the differing map codomains, but `Map.intersectionWith` seems more direct.

The comment caught my eye and prompted this quick PR. HTH.

### CODE REVIEW

**Comment by nfrisby** [comment]
I'd guess that `lookupMax . intersectionWith (,)` does as little work as possible, but I'm not totally sure. Might be worthwhile to confirm that this diff doesn't introduce a bit more work in the presumably common case of the common version being within one or two.

**Comment by coot** [comment]
I don't think that performance will ever be an issue here.  Using `Map.`intersectWith` is indeed nicer, and easier to grasp what's going on.

**Review by coot — APPROVED** [review]
LGTM

**Comment by nfrisby** [comment]
I'm sorry for the delay; I was confused. My rebase just now to current `master` was automatic. borsing now. 👍 

bors r+

**Pull request merged**
