### PR TITLE
protocol: add PraosProtocolSupportsNode class

### PR DESCRIPTION
**Pull request by nfrisby**
Fixes input-output-hk/cardano-node#3864. Single commit; see its message.

### CODE REVIEW

**Review by nc6 — APPROVED** [review]
Looks reasonable for a stopgap patch.

**Review by dcoutts — APPROVED** [review]
LGTM.

I agree that this is a reasonable intermediate solution, and added some thoughts for a nicer solution on the ticket
https://github.com/input-output-hk/cardano-node/issues/3864#issuecomment-1132933288

**Comment by nfrisby** [comment]
bors merge

**Comment by nfrisby** [comment]
bors cancel

**Comment by nfrisby** [comment]
bors merge

**Pull request merged**
