### PR TITLE
Update win32 version

### PR DESCRIPTION
**Pull request by kderme**
This pr updates the `Win32` version, given some recent changes on katip and iohk-monitoring-framework.
The new version allows to revert an ugly hack we did to support seeking in windows.

### CODE REVIEW

**Comment by mrBliss** [comment]
Don't forget to update the nix stuff.

**Comment by kderme** [comment]
@mrBliss I fixed nix. 

Maybe we want to ask the opinion of people at the network team for this pr?

**Comment by mrBliss** [comment]
> @mrBliss I fixed nix.
> 
> Maybe we want to ask the opinion of people at the network team for this pr?

@coot You're working on Windows support. What's your opinion?

**Comment by coot** [comment]
Yes I am fine with it.

**Comment by mrBliss** [comment]
One thing that might be best to check before we merge this is whether all downstream repos can handle this dependency change on Win32: cardano-node, cardano-byron-proxy, and cardano-explorer. I don't think it will be an issue, though.

**Comment by mrBliss** [comment]
btw, the `stack.yaml` still pins the Win32 version to 2.5.4.1: https://github.com/input-output-hk/ouroboros-network/pull/1160/files#diff-fafd0cdcd559a7b124cc61c29413fb54R74

**Comment by mrBliss** [comment]
Subsumed by #1164.

**Pull request closed without merging**
