### PR TITLE
chain sync protocol type arguments

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Comment by coot** [comment]
@avieth there are two use cases:

* `Point header` is used for: agreeing on common point, sending rollback instruction
* `tip` is for sending information about tip: currently it's also `Point header`, but for frontend reporting and pipelining we will use `(Point header, BlockNo)`.

As a side benefit of making `tip` a polymorphic type variable: at least in `ouroboros-network` we cannot confuse `tip` with `Point header`.

**Comment by coot** [comment]
Right this is for the sake of simplicity, but  it actually forced the `ouroboros-consensus` peers to use the right type (though it just shifted coercions around).

**Comment by coot** [comment]
> Rather complicated because it uses a type family HeaderHash and so often if you want to use it you need to know more about the header type.

It's the only use case so there's no way to escape `HeaderHash` family at the moment; no need to generalise too early. And we still have type safety.   In `ouroboros-consensus` there might be other constraints like `Typeable` on it, so it's better to have a concrete type anyway.

> Was there some bug in which two chain sync peers using different point types failed to communicate?

No, it's just matter of elegance that the client and server use the same type without casting.  And in the server you only need to cast when you read something off your chain and want to pass it to the client.  The same could be achieved with `piont` parameter though.

**Comment by coot** [comment]
Right, since now you're using the same as in `ouroboros-consensus` we can standardize this; It will be easier to review different clients written by various teams. 

The `ChainDB` presents `Point blk` which needs to be casted to `Point (Header blk)`, so there is  `Point blk ~ Point (Header blk)`.

**Comment by coot** [comment]
Another problem with type aliasing is that we will need quite a few of them which will make the API unnecessary large (`Type`, `Client` and `Server` modules expose quite a few constructors which will need type aliases).

@dcoutts maybe you could help here.

**Comment by edsko** [comment]
Closed in favour of #950.

**Pull request closed without merging**
