### PR TITLE
Windows CI using github-actions

### PR DESCRIPTION
**Pull request by coot**
Building natively and running tests using a VM provided by `github` using `github-actions`.

### CODE REVIEW

**Comment by coot** [comment]
@disassembler I am really glad you suggested `github-actions`! Let's see how the machines run :).

**Comment by dcoutts** [comment]
In case people are confused, this is about _building_ on windows, and running test. Not just about the windows cross-compilation that we already do.

**Comment by coot** [comment]
Related experiment #1809

**Comment by coot** [comment]
bors: merge

**Pull request merged**
