### PR TITLE
Upgrade stylish-haskell to 0.12.2.0

### PR DESCRIPTION
**Pull request by EncodePanda**
Upgrading stylish-haskell via tools

Regarding imports sorting please see https://github.com/input-output-hk/ouroboros-network/pull/2968#issuecomment-793785214

### CODE REVIEW

**Comment by EncodePanda** [comment]
@nfrisby this is good to go, right?

**Review by nfrisby — APPROVED** [review]
LGTM. We've concluded that the style changes are due to `stylish-haskell` switching from `haskell-src-exts` to `ghc-lib-parser`.

It's not totally clear if they were all intentional or will be persisted in future versions (the CHANGELOG didn't mention them specifically), but none of this is critical anyhow. We expect they won't change again anytime soon.

**Comment by EncodePanda** [comment]
@nfrisby regarding sorting it's a bit more complicated, explained here https://github.com/input-output-hk/ouroboros-network/pull/2968#issuecomment-793785214

**Comment by EncodePanda** [comment]
bors merge

**Pull request merged**
