### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by erikd**
Specifically, use cardano-ledger-specs version after cardano-ledger
has been merged into it.

### CODE REVIEW

**Comment by mrBliss** [comment]
CI fails because the Shelley golden tests fail. It looks like something related to hashes changed. Is that intentional?

To update a golden test: replace the list of CBOR terms with an empty one and run it again, it will print the expected output.

**Comment by erikd** [comment]
Need to wait for Windoze :/

bors cancel

**Comment by mrBliss** [comment]
> Need to wait for Windoze :/
> 
> bors cancel

You can bors before the Windows job finished.

**Comment by mrBliss** [comment]
Documenting this for myself: the golden tests changed because the `networkMagicId` of `ConcreteCrypto` (which we use for the golden tests) changed from `Offline` to `Testnet` (https://github.com/input-output-hk/cardano-ledger-specs/pull/1465/commits/338a82114d09dac223242e6060fdaa56a0d8f84b#diff-9831fea0a1f20a6d53bdec4b976d7a30R50) and this value is included in the hash of a header.

**Pull request merged**
