### PR TITLE
Improve mux tracing

### PR DESCRIPTION
**Pull request by coot**
This PR consist of three patches, the last one is not at all about tracing:

- network-mux: replaced 'Dying' with MuxTraceTerminating
  Mux is not dying anymore when a mini-protocol terminates, let's reflect that
  in the trace.
- network-mux: sligtly nicer Show instance for MuxTrace
- network-mux: filling completionVar should never block
  ~Might be **controverial**!~ It is sensible to throw an exception if it blocks.

### CODE REVIEW

**Review by karknu — APPROVED** [review]
LGTM

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Pull request merged**
