### PR TITLE
Bump ledger dep

### PR DESCRIPTION
**Pull request by Jimbo4350**

### CODE REVIEW

**Comment by lehins** [comment]
This is not the full update. More changes are needed. Feel free to cherry pick this commit: 4e4f2e1bf31c442678a9b19bb3ead02fe44e401e

**Comment by lehins** [comment]
@nfrisby This PR tries to update new ledger, however we also need to bump up base and if we do that there will be a problem with EpochInfo that is only apparent at runtime. That is because we haven't accounted to the change to EpochInfo, which I know you are working on, see this bogus commit for what I mean: 02f8eb1accf8964d201279329720d07fa4fa51de

**Comment by nfrisby** [comment]
FYI @Jimbo4350 @lehins I have pushed a branch here and to `cardano-node` such that `exe:cardano-node` builds.

Would you please squash those commits into your PR here and into your downstream commit?

`ouroboros-network`:

```
$ git lg -4 origin/nfrisby/vasil-hf-WIP 
df67b24c6 - (origin/nfrisby/vasil-hf-WIP) TOSQUASH fixup Alexei's commit for Shelley.Node.TPraos (6 minutes ago) <Nicolas Frisby>
71486753c - TOSQUASH undo Alexei's commit's changes to Shelley.Node (6 minutes ago) <Nicolas Frisby>
9ef4e40f9 - TOSQUASH define the epochInfoSlotLength_ field too (65 minutes ago) <Nicolas Frisby>
84273fed3 - (origin/jordan/bumpdeps-20220518) Bump up plutus and base (2 hours ago) <Alexey Kuleshevich>
```

and `cardano-node`:

```
$ git lg -5 nfrisby/dep-bump-protocol-in-block 
dedec0d8f - (HEAD -> nfrisby/dep-bump-protocol-in-block, origin/nfrisby/dep-bump-protocol-in-block) node: SplitMap was removed, use normal Map (6 minutes ago) <Nicolas Frisby>
66d9efa58 - api: SplitMap was removed, use normal Map (9 minutes ago) <Nicolas Frisby>
1c04ea6c2 - api: Babbage has _coinsPerUTxOByte instead of _coinsPerUTxOWord (10 minutes ago) <Nicolas Frisby>
591dee9b3 - api: Data.VMap instead of Data.Compact.Map (10 minutes ago) <Nicolas Frisby>
cf3e0c75e - (origin/jordan/dep-bump-protocol-in-block) Further cabal.project file changes. Merge with initial cabal.project file commit (48 minutes ago) <Jordan Millar>
```

**Comment by nfrisby** [comment]
Also, ^^^ I was building with `cardano-base 8fe904d629194b1fbaaf2d0a4e0ccd17052e9103` and `cardano-ledger 972c7cfa4196014343fc461e3dcdb55eb906bd8c` which are currently the `master` branch tips.

**Comment by Jimbo4350** [comment]
> Please see my above comment where I shared my commits on top of these that let me build `cardano-node`.
> 
> I asked you to squash them, but I wasn't really thinking -- I just said that because you're the authors of this PR. I'll squash and create another PR and mark you two as reviewers.

Let me cherry pick your commits from your node branch and squash them. I'd rather not have another PR in node.

**Comment by nfrisby** [comment]
I closed this -- I opened PR #3753 instead. Thanks for contributing these commits.

**Pull request closed without merging**
