### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by dcoutts**

### CODE REVIEW

**Comment by dcoutts** [comment]
Need to fix sha256 hashes...

**Comment by mrBliss** [comment]
@dcoutts I was also bumping the dependency on `cardano-ledger` in https://github.com/input-output-hk/ouroboros-network/pull/1793. I like your fix for `generateGenesisConfig` better than mine.

One problem is that the ledger state changed, breaking the golden tests, see
https://github.com/input-output-hk/ouroboros-network/pull/1793#issuecomment-598368039. How should we proceed? Let it change, requiring a replay from genesis on the startup after upgrading to the next version?

**Comment by edsko** [comment]
Note that 5fa286f0efc5cab4ec3eaa33f44a2ccec0cb207c (introduction of `RealPoint` #1706 ) also would have broken the ledger state (probably).

**Comment by dcoutts** [comment]
The important changes have now been included in #1793. The remaining changes are unimportant. Closing.

**Pull request closed without merging**
