### PR TITLE
cabal.project: update dependencies

### PR DESCRIPTION
**Pull request by nfrisby**
This brings each of the changed deps to their latest merged PR as of 2022 May 26.

### CODE REVIEW

**Review by nc6 — APPROVED** [review]

**Comment by nc6** [comment]
bors merge

**Review by amesgen — CHANGES_REQUESTED** [review]
This time, the Hydra failures are actually not spurious, but three golden tests in ouroboros-consensus-cardano-test are actually failing:

```
cabal run ouroboros-consensus-cardano-test:test -- -p '$0 ~ /CardanoNodeToClientVersion9.Result.Result_Babbage_EmptyPParams/ || $0 ~ /LedgerState_Babbage/'
```

Accepting them yields:

```
 $ git diff --stat
 ouroboros-consensus-cardano-test/test/golden/QueryVersion2/CardanoNodeToClientVersion9/Result_Babbage_EmptyPParams | Bin 55 -> 55 bytes
 ouroboros-consensus-cardano-test/test/golden/disk/ExtLedgerState_Babbage                                           | Bin 1050 -> 1050 bytes
 ouroboros-consensus-cardano-test/test/golden/disk/LedgerState_Babbage                                              | Bin 676 -> 676 bytes
 3 files changed, 0 insertions(+), 0 deletions(-)
```

@nc6 Can you confirm that these are expected? If so, I will push a commit accepting these changes here.

**Comment by nc6** [comment]
Just checking...

**Comment by nc6** [comment]
The `emptyPParams` change is expected.

**Comment by nfrisby** [comment]
I made a mistake. It has now been fixed. The current tip is Esgen's commit rebased onto master to pick up PR #3775.

**Comment by nfrisby** [comment]
It failed due to a cached `ouroboros-network` test failure on Hydra. I told Hydra to restart that failure (after notifying #network about it on the Slack).

**Pull request merged**
