### PR TITLE
Explicit conensus traces

### PR DESCRIPTION
**Pull request by coot**
This adds block fetch tracers to `NodeParams`.  This gives the power to
the user to instantiate the traces.  This is useful for debuging block
fetch logic.

### CODE REVIEW

**Comment by mrBliss** [comment]
Can't we multiplex all tracers into one tracer (the one we have either with `String` or a sum type of all trace events)? Is there a reason for not doing it that way?

**Comment by coot** [comment]
This way we give more power to the user which events to trace (and how to trace them).

**Comment by coot** [comment]
@mrBliss if you want to have a sum type, that's fine for me. I'd just would like to have something working for now and later you could replace it with something more suitable.  Using a `Trace m String` everywhere might not be a good idea, since it doesn't say what kind of events go through this trace, but either a sum type or a product of traces (as in this patch) does not share this flaw.

**Comment by coot** [comment]
Perfect, thanks @mrBliss 

bors r+

**Pull request merged**
