### PR TITLE
Updated cardano-base & avoid libsecp256k1 on Windows

### LINKED ISSUE #3678: Install libsecp256k1 on Windows in GH actions.
CI is failing due to missing `libsecp256k1` dependency introduced in #3661.

### PR DESCRIPTION
**Pull request by coot**
Closes #3678, `libsecp256k1` is not available on Windows.

### CODE REVIEW

**Comment by amesgen** [comment]
FYI: In https://github.com/input-output-hk/haskell.nix/pull/1424, @hamishmack added the possibility to download a Windows binary of libsecp256k1; this might be an alternative to this PR.

**Comment by hamishmack** [comment]
I wonder if these need to append to PKC_CONFIG_PATH somehow?

https://github.com/input-output-hk/ouroboros-network/blob/de22b3505ab84a98701f45411fb4fa21db0e2aec/.github/workflows/build.yml#L73

https://github.com/input-output-hk/ouroboros-network/blob/de22b3505ab84a98701f45411fb4fa21db0e2aec/.github/workflows/build.yml#L123

**Comment by hamishmack** [comment]
Can you `echo "$PKG_CONFIG_PATH"` in the failing step to see what value it has?

**Comment by amesgen** [comment]
> Can you `echo "$PKG_CONFIG_PATH"` in the failing step to see what value it has?

See https://github.com/input-output-hk/ouroboros-network/runs/5816059242?check_suite_focus=true

**Comment by hamishmack** [comment]
I wonder if it should be: 

```
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$(readlink -f secp256k1/lib/pkgconfig)"
```

To keep libsodium in the path.  But if that is the case why was it secp256k1 that it could not find?

**Comment by amesgen** [comment]
Just pushed 4e887f581f7dcc457985f5303d9080a57a5275bf to append to PKG_CONFIG_PATH, but I agree that one would expect that libsodium and not libsecp256k1 could not be found before.

Also, I opened #3687 which I guess is a better place to discuss this.

**Comment by coot** [comment]
Closing this one in favour of #3687.

**Pull request closed without merging**
