### PR TITLE
Add simple `hie.yaml`

### PR DESCRIPTION
**Pull request by amesgen**
# Description

This is necessary due to a bug somewhere in HLS 1.7 vs 1.8, which was upgraded in #4078.

# Checklist

- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Commits have useful messages
    - [ ] New tests are added if needed and existing tests are updated
    - [ ] If this branch changes Consensus and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../ouroboros-consensus/docs/interface-CHANGELOG.md)
    - [ ] If this branch changes Network and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../docs/interface-CHANGELOG.md)
    - [ ] If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.
- Pull Request
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [ ] Reviewer requested

### CODE REVIEW

**Review by bolt12 — APPROVED** [review]

**Comment by amesgen** [comment]
bors merge

**Review by bolt12 — APPROVED** [review]

**Comment by angerman** [comment]
Somehow the windows builder (or ghcup) mutated underneath :(

**Comment by amesgen** [comment]
> Somehow the windows builder (or ghcup) mutated underneath :(

Yes, this is horrible, if you have any idea what to try in order to fix this, I would be very thankful. I only tried switching to cabal 3.8 so far, which [didn't help](https://github.com/input-output-hk/ouroboros-network/commits/amesgen/windows-sisyphus).

**Comment by amesgen** [comment]
bors retry

**Pull request merged**
