### PR TITLE
Hard-code expected results as CBOR for golden files instead of using files

### LINKED ISSUE #1351: Golden tests can fail due to relative paths
I'm assuming this failure is due to relative paths and the process's working directory. Ideally the test wouldn't be sensitive to that.

```
$ cd ouroboros-network
$ cabal v2-run ouroboros-consensus:test:test-consensus
...
    Golden tests
      ChainState:                                         FAIL
        Exception: test-consensus/golden/cbor/byron/ChainState: openBinaryFile: does not exist (No such file or directory)
      LedgerState:                                        FAIL
        Exception: test-consensus/golden/cbor/byron/LedgerState: openBinaryFile: does not exist (No such file or directory)
      GenTxId:                                            FAIL
        Exception: test-consensus/golden/cbor/byron/GenTxId: openBinaryFile: does not exist (No such file or directory)
...
$ ls -1 ouroboros-consensus/test-consensus/golden/cbor/byron/
ChainState
GenTxId
LedgerState
```

After running `ln -s ouroboros-consensus/test-consensus`, the tests pass.

cc: @mrBliss

### PR DESCRIPTION
**Pull request by mrBliss**
Fixes #1351.

Using files to store the expected results for golden files, and thus relative paths, was a PITA: see #1351 + it was causing problems in #1851.

This PR introduces `Test.Util.Golden`, which takes the expected result as a CBOR `FlatTerm`. No more files, hurray! Using a `FlatTerm` will make diffing much easier.

### CODE REVIEW

**Comment by mrBliss** [comment]
This is an alternative approach to #1852. The `FlatTerm` is more verbose, making the files much longer, but when it changes, the diff will be much clearer (I'm using http://hackage.haskell.org/package/tree-diff for diffing).

**Comment by nfrisby** [comment]
The more transparent diff seem like a significant advantage to me.

To mitigate the file length -- at the cost of the transparency of the git diff -- you could only force newlines after `TkBytes`, letting the other token ctors accumulate on a single ~79 character line. Or even just let all token ctors accumulate, in case there's a short `TkBytes`. I don't have much experience inspecting flatterms; maybe that presentation would be far less helpful.

FWIW, the long files don't seem too problematic. If it becomes an issue, we can separate egregiuos offenders into their own modules.

**Comment by mrBliss** [comment]
> The more transparent diff seem like a significant advantage to me.
> 
> To mitigate the file length -- at the cost of the transparency of the git diff -- you could only force newlines after `TkBytes`, letting the other token ctors accumulate on a single ~79 character line. Or even just let all token ctors accumulate, in case there's a short `TkBytes`. I don't have much experience inspecting flatterms; maybe that presentation would be far less helpful.
> 
> FWIW, the long files don't seem too problematic. If it becomes an issue, we can separate egregiuos offenders into their own modules.

Yeah, I think the benefits outweigh the costs, indeed. I'm not keen on letting them accumulate on a line, because that either means manually wrapping lines or making the formatter more complex so that the copy-pastable output already does the wrapping.

**Comment by mrBliss** [comment]
Uggh, a timing test failed because CI is overloaded.

**Comment by mrBliss** [comment]
bors retry

**Pull request merged**
