### PR TITLE
Change networkErrorPolicy

### PR DESCRIPTION
**Pull request by coot**
Be permissive in case of MuxBearerClosed && IOExceptions (during read
/ write operations).

The change is well explained in the code.  Currently, when a remote peer is not interested in our chain it will close the connection and the node shuts down connection to the peer for 20s - not long but there's no need to do that at all.

### CODE REVIEW

**Comment by coot** [comment]
In this case the remote node will only suspend its consumer.  The consensus error policy is [here](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs#L129)

**Comment by karknu** [comment]
> In this case the remote node will only suspend its consumer. The consensus error policy is [here](https://github.com/input-output-hk/ouroboros-network/blob/master/ouroboros-consensus/src/Ouroboros/Consensus/Node/ErrorPolicy.hs#L129).

Consensus has consumer and producer running on different ports, so they are in effect different peers.

**Comment by coot** [comment]
That's true for now, but in the future this might not be the case any more.

**Comment by coot** [comment]
I think you're not right: we bind the address and the `PeerState` is per address not per connection: so both inbound and outbound connections for that remote peer will use the same key in `PeerStates` map.

**Comment by karknu** [comment]
> That's true for now, but in the future this might not be the case any more.

I know, since I'm very much working on that. :)
https://github.com/input-output-hk/ouroboros-network/tree/karknu/i_and_r
https://github.com/input-output-hk/ouroboros-network/tree/karknu/mux_lazy

**Comment by karknu** [comment]
> I think you're not right: we bind the address and the `PeerState` is per address not per connection: so both inbound and outbound connections for that remote peer will use the same key in `PeerStates` map.

The subscription worker is run with port 0, so will get a free ephemeral port. The server will bind to the configured port number.
However in the future they will use the same port number, see the `karknu/i_and_r` branch.

**Comment by coot** [comment]
You're right then :).  Is there a reason why we're not binding to the actual port?

Still this change will protect us in the future.  I'll update the comment though.

**Comment by karknu** [comment]
> You're right then :). Is there a reason why we're not binding to the actual port?
We do bind to the ephemeral port too, sorry I should have made that clear.

**Pull request closed without merging**
