### PR TITLE
Release docs pdf on hydra

### PR DESCRIPTION
**Pull request by jbgi**

### CODE REVIEW

**Comment by jbgi** [comment]
PDFs here: https://hydra.iohk.io/build/4042241

**Review by coot — APPROVED** [review]
LGTM

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
One thing though: what is a link to the latest build (without job number).  This would be useful to include in a `README.md` file.

**Comment by coot** [comment]
Thanks

**Pull request merged**
