### PR TITLE
Update ledger

### PR DESCRIPTION
**Pull request by lehins**
Brings ledger and consensus in sync.

Also took care of a `TODO`: relax constraint from `Applicative` to `Functor`

Updated GithubActions CI to pin secp256k1

### CODE REVIEW

**Review by nc6 — APPROVED** [review]

**Comment by nc6** [comment]
Though note also https://github.com/input-output-hk/ouroboros-network/pull/3686

**Comment by lehins** [comment]
@nc6 Yes, #3686 is very similar, however target branch is not `master`, so at some point fast forward or a merge will bring these two PRs together

**Comment by lehins** [comment]
bors merge

**Comment by amesgen** [comment]
Rebasing on top of/merging master should fix the bors failure (as of #3687, which fixed the GH Windows job failure due to missing libsecp256k1).

**Comment by lehins** [comment]
@amesgen Thank you for letting me know. It's done. Will wait now for CI to turn green :smile:

**Comment by nfrisby** [comment]
@lehins can you cleanup/refine the PR description regarding secp256k1 and Windows? The PR descriptions in this repo end up in the merge commits. Thanks much for the PR!

**Comment by lehins** [comment]
> The PR descriptions in this repo end up in the merge commits.

That's great, didn't know that.

Cleaned up.

**Comment by lehins** [comment]
bors merge

**Pull request merged**
