### PR TITLE
Update to latest cardano-ledger-specs

### PR DESCRIPTION
**Pull request by nc6**
This pulls in two things:

- Crypto changes in base
- Key changes in cardano-ledger-specs

### CODE REVIEW

**Comment by nc6** [comment]
I think it is now only used in the tests

**Comment by edsko** [comment]
Ah, so we can't remove it from `Protocol.Abstract` yet?

**Comment by nc6** [comment]
Ah, sorry, it's also still used in `evalCertified` for VRF.

**Pull request merged**
