### PR TITLE
Add Windows as a hydra CI required job

### PR DESCRIPTION
**Pull request by dcoutts**
Just building, via cross compilation, not running tests.

### CODE REVIEW

**Comment by dcoutts** [comment]
Looks like we're hitting problems building the cddl tests (needs perl) and the db-converter tool for some reason. Neither of those are needed, so we could disable them both, but my nix foo isn't up to it. Help please :-)

**Comment by mrBliss** [comment]
> Looks like we're hitting problems building the cddl tests (needs perl) and the db-converter tool for some reason. Neither of those are needed, so we could disable them both, but my nix foo isn't up to it. Help please :-)

I have reproduced the failing nix job for [`validate-mainnet`](https://hydra.iohk.io/build/2026633) locally and found out the problem is that the script expects `db-converter` while on Windows it is actually `db-converter.exe`. cc: @nc6. I'm also a nix noob, so I dont't know how to fix it or disable it :flushed:.

**Comment by dcoutts** [comment]
We believe the solution here is to:
1. disable the CDDL test (done)
2. disable running tests under wine.

Running tests under wine is a neat trick, but it turns out is not that useful for the network code because we depend crucially on testing the behaviour with actual Windows I/O, using the behaviour of the real windows I/O subsystem. We also get failures under wine that do not occur on real Windows.

**Comment by dcoutts** [comment]
It looks like this is resolved by #1835

**Pull request closed without merging**
