### PR TITLE
Support GHC 9.4

### PR DESCRIPTION
**Pull request by coot**
# Description

- ouroboros-network-api: removed encodedTipSize, encodedPointSize
- Experimental ghc-9.4 support
- Updated prologue file

_description of the pull request, if it fixes a particular issue it should link the PR to a particular issue, see [ref](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=)_

# Checklist

- Branch
    - [x] Commit sequence broadly makes sense
    - [x] Commits have useful messages
    - [ ] The documentation has been properly updated
    - [x] New tests are added if needed and existing tests are updated
    - [ ] If this branch changes Network and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../docs/interface-CHANGELOG.md)
    - [ ] If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.
- Pull Request
    - [x] Self-reviewed the diff
    - [x] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [x] Reviewer requested

### CODE REVIEW

**Comment by coot** [comment]
Unfortunately `cabal haddock-project` does not support public libraries which we use.

**Review by lehins — APPROVED** [review]
:+1:

**Review by Jasagredo — APPROVED** [review]
So network was almost already compatible with 9.4 if it wasn't for that TypeOperator pragma. Nice!

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors cancel

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Pull request merged**
