### PR TITLE
Enable -Werror in all packages

### PR DESCRIPTION
**Pull request by coot**
- `io-sim`
- `io-sim-classes`
- `typed-protocols`
- `ouroboros-consensus`

`ouroboros-network` allready builds with -Werror

### CODE REVIEW

**Comment by karknu** [comment]
This breaks compilation on windows :|

**Comment by angerman** [comment]
@karknu are you referring to the failures in CI on hydra?

```
001a:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x69ebd3de, context 0x8d66f0, init_notify 0, handle 0x11cfa10): stub
[         iserv-proxy] Created socket for 127.0.0.1:9126
wine: configuration in '/build' has been updated.
0009:err:module:import_dll Library libffi-6.dll (which is needed by L"Z:\\nix\\store\\87vf8yn5ih3xxxnamv3cwa6jxj481fi0-remote-iserv-8.6.4-exe-remote-iserv-x86_64-pc-mingw32\\bin\\remote-iserv.exe") not found
0009:err:module:attach_dlls Importing dlls for L"Z:\\nix\\store\\87vf8yn5ih3xxxnamv3cwa6jxj481fi0-remote-iserv-8.6.4-exe-remote-iserv-x86_64-pc-mingw32\\bin\\remote-iserv.exe" failed, status c0000135
```

I believe these to be independent of `-Werror`, and rather an issue with stupid dlls.  This has been fied in a separate iohk project where we needed to copy the libffi dll into the executable path as well.

@karknu please let me know if you are referring to this or some other windows build issue.

**Comment by coot** [comment]
@karknu afaik we don't build on windows on CI, and this change only affects CI (nix), not `cabal new-build`.

**Comment by karknu** [comment]
I was referring to warnings in `cabal new-build` on windows, but if CI fails before that on windows it doesn't matter.

**Comment by coot** [comment]
@karknu then we can merge it.

bors r+

**Pull request merged**
