### PR TITLE
SRE-203: Add check-stylish-network to Hydra

### PR DESCRIPTION
**Pull request by craigem**

### CODE REVIEW

**Comment by EncodePanda** [comment]
please do not merge this PR until we fix issues introduced by https://github.com/input-output-hk/ouroboros-network/pull/3431

**Comment by craigem** [comment]
> please do not merge this PR until we fix issues introduced by #3431

Please detail the problems you've found in PR #3431 as we've not been able to identify any :smiley:

**Comment by craigem** [comment]
I believe this PR is no longer blocked - can you confirm @EncodePanda ?

I'll get this PR up to date and submit it for review.

**Review by coot — APPROVED** [review]
LGTM,

I would like to avoid duplication and use a single script.  This will avoid possible mistake that in the future one will modify only one and not the one that is used by ci.  But this can be done in a seprate PR.

**Comment by coot** [comment]
@craigem hydra reports this error
```
unpacking source archive /nix/store/f9pmv139n4nzpcx15186y1ixjx5k6kcy-4v3h9li80vhhjn3jyy0aaj2q9ryr2vfh-source
source root is 4v3h9li80vhhjn3jyy0aaj2q9ryr2vfh-source
stylish-haskell: ouroboros-network-framework/test/Test/Ouroboros/Network/Server2.hs: commitBuffer: invalid argument (invalid character)
```

I wasn't able to reproduce this locally.  This might be related to locale setting, could you try to set an `UTF-8` locale, e.g. this might fix it:
```
export LC_ALL=C.UTF-8
```

**Comment by craigem** [comment]
Added the `export` and Hydra now passes.

Also rebased on `master`.

**Comment by coot** [comment]
great, thanks @craigem 

bors merge

**Pull request merged**
