### PR TITLE
Fix and unify stylish-haskell checks 

### PR DESCRIPTION
**Pull request by amesgen**
Previously, the nix stylish-haskell checks where only checking that the files *can* be formatted (no errors due to e.g. CPP), but not that they actually are formatted, as `stylish-haskell -i` will succeed with exit code 0 even if it some of its input files were not already formatted. This PR fixes this by using the `exit_code: error_on_format` of stylish-haskell.

In addition:
  - We reuse the scripts in `scripts/ci` such that people can easily run stylish-haskell in the same way as it is checked in CI.
  - We use `cleanGit` to only copy the git-tracked files to the nix store. Previously, the entire local development directory would be copied (easily >1GB). This subsumes #3669.
  - `checks.styles.check-stylish-network` is removed and part of `nix-build -A checks.styles.check-stylish`.

To test this:
  1. Introduce some change which makes the file unformatted.
  2. Check that `nix-build -A checks.styles.check-stylish` fails.

### CODE REVIEW

**Comment by amesgen** [comment]
There seem to be some additional files which have to be excluded due to CPP, will fix.

**Comment by amesgen** [comment]
Hmm, the Hydra checkout of the repo does not include the `.git` dir, so `git diff` does not work. Looking for a workaround...

**Comment by amesgen** [comment]
Now using the `exit_code: error_on_format` option of stylish-haskell.

**Comment by amesgen** [comment]
This is now ready for review, sorry for not opening this as a Draft PR first. The Hydra failure for test-storage is not related (known to be flaky).

**Review by coot — APPROVED** [review]
LGTM

**Comment by amesgen** [comment]
Windows CI seems to be failing due to an OOM error. I am merging it manually, as we will have bors run when merging #3719 either way.

**Pull request merged**
