### PR TITLE
Update ledger dependency

### PR DESCRIPTION
**Pull request by dcoutts**
The _stkCreds and _stPools are gone. The rewards mapping is now just the
plain Credendial and not the stake address wrapper type (with the
network).

### CODE REVIEW

**Comment by dcoutts** [comment]
There are some golden test updates needed but I cannot find where the golden examples live any more.

Changes:
```        ,TkInt 1
        ,TkListLen 3
        ,TkListLen -5 +3
        ,TkMapLen 2
        ,TkBytes
           "U\165@\b\173\ESC\165\137"
```
This comes from ledger commit
```commit 3f7d735fefebfba18058140fcdb8edb093737407
Author: Thomas Winant <thomas@well-typed.com>
Date:   Mon Jul 20 15:22:04 2020 +0200

    Use correct listLen for PrtclState
    
    Previously, it was not valid CBOR.
```
Other removals are almost certainly due to the removal of _stkCreds and _stPools from the ledger state.

**Comment by mrBliss** [comment]
> There are some golden test updates needed but I cannot find where the golden examples live any more.
> 
> Changes:
> 
> ```
>         ,TkListLen 3
>         ,TkListLen -5 +3
>         ,TkMapLen 2
>         ,TkBytes
>            "U\165@\b\173\ESC\165\137"
> ```
> 
> This comes from ledger commit
> 
> ```
> Author: Thomas Winant <thomas@well-typed.com>
> Date:   Mon Jul 20 15:22:04 2020 +0200
> 
>     Use correct listLen for PrtclState
>     
>     Previously, it was not valid CBOR.
> ```

I'll update them.

To update the golden test results, delete the `ouroboros-consensus*/test/golden` folder in question and run the tests again, that will recreate the golden files.

**Comment by mrBliss** [comment]
Tests are failing with
```
      Exception:
        Invalid genesis config:
        You have specified an 'updateQuorum' which is too small compared to the number of genesis nodes. You requested 1, but given 2 genesis nodes 'updateQuorum' must be greater than 1
```

Will fix

**Comment by dcoutts** [comment]
bors merge

**Pull request merged**
