### PR TITLE
Bump ledger.

### PR DESCRIPTION
**Pull request by nc6**
This incorporates the following changes:
- A rewrite of `UnitInterval` and other bounded types.
  (https://github.com/input-output-hk/cardano-ledger-specs/pull/2343)
- Fractional pricing for Plutus scripts. This is required because
  otherwise even the simplest scripts were costing too much.
  (https://github.com/input-output-hk/cardano-ledger-specs/pull/2347)
- A few otherwise trivial changes (e.g. moving `Cardano.Ledger.Address`)

### CODE REVIEW

**Review by edsko — APPROVED** [review]
LGTM

**Review by nfrisby — APPROVED** [review]
Yep 👍

**Comment by nfrisby** [comment]
The Hydra failure is the golden tests catching a change in the serialization of a Shelley era (ie the predecessor of Allegra) `LedgerState`. There's a couple new `TkTag 30`s in there. I'm guessing the other `ShelleyBased` eras would also have failed if the Cardano golden tests had ran.

**Comment by JaredCorduan** [comment]
> @nc6 The Hydra failure is the golden tests catching a change in the serialization of a Shelley era (ie the predecessor of Allegra) `LedgerState`. There's a couple new `TkTag 30`s in there. ~I'm guessing the other `ShelleyBased` eras would also have failed if the Cardano golden tests had ran.~
> 
> After clicking around in a very slow Hydra, I found the corresponding Cardano golden tests, and they do show that the other eras also have serialization changes. https://hydra.iohk.io/build/6833194/nixlog/2

@nfrisby thank you! I'm sad we did not catch this in our tests. The fix is here: https://github.com/input-output-hk/cardano-ledger-specs/pull/2368

**Comment by nc6** [comment]
bors merge

**Comment by nc6** [comment]
bors retry

**Comment by nc6** [comment]
bors retry

**Pull request merged**
