### PR TITLE
Remove Counter module

### PR DESCRIPTION
**Pull request by newhoggy**
Backing out some changes that should not have been merged.

### CODE REVIEW

**Review by nfrisby — APPROVED** [review]
Approved. Thanks much.

**Review by coot — APPROVED** [review]

**Review by deepfire — APPROVED** [review]
LGTM!

**Comment by nfrisby** [comment]
@newhoggy Is this ready for merge? If so, please rebase and invoke `bors`.

**Comment by coot** [comment]
@newhoggy if you're not planning to add anything in here, please merge.

**Pull request closed without merging**
