### PR TITLE
Add parallel tests

### PR DESCRIPTION
**Pull request by kderme**
Builds on top of https://github.com/input-output-hk/ouroboros-network/pull/1180
Addresses https://github.com/input-output-hk/ouroboros-network/issues/1188
This pr adds paralle qsm tests for the VolatileDB.
It doesn't use the MockFS like sequential tests, but the real filesystem.
Only the basic api is supported for now: no simulated errors or corruptions.

### CODE REVIEW

**Comment by mrBliss** [comment]
> It doesn't use the MockFS like sequential tests, but the real filesystem.

I have not reviewed this PR yet, but why do you use the real file system instead of the MockFS?

> Only the basic api is supported for now: no simulated errors or corruptions.

That's fine.

**Comment by kderme** [comment]
> I have not reviewed this PR yet, but why do you use the real file system instead of the MockFS?

Can the MockFS detect race conditions i.e. linearizability violations?

**Comment by mrBliss** [comment]
> > I have not reviewed this PR yet, but why do you use the real file system instead of the MockFS?
> 
> Can the MockFS detect race conditions i.e. linearizability violations?

I don't follow. Can the real file system detect race conditions? Does this matter? Maybe you can give an example of how things go wrong with the MockFS?

**Comment by kderme** [comment]
> > > I have not reviewed this PR yet, but why do you use the real file system instead of the MockFS?
> > 
> > 
> > Can the MockFS detect race conditions i.e. linearizability violations?
> 
> I don't follow. Can the real file system detect race conditions? Does this matter? Maybe you can give an example of how things go wrong with the MockFS?

In the sequential case, we have qsm tests for the FS (these prove the equivalence of MockFS with the real filesystem) and then the volatileDB tests run on the MockFS. 
However there are currently no qsm tests for the FS in the parallel case. So having volatileDB tests on the MockFS will only say half the story.

**Comment by Jasagredo** [comment]
Probably not applicable anymore, also probably will be superseeded by IOSimPOR + q-d. cc @dnadales

**Comment by dnadales** [comment]
Thanks for checking @Jasagredo. @kderme I'll close this, let me know if you still want to merge it. I'm really sorry that you got no feedback :( This should not happen.

**Pull request closed without merging**
