### PR TITLE
Expose connection manager transitions tracer

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Comment by coot** [comment]
This is a draft until we can merge tracer changes to the tracing subsystem of the `cardano-node`.

**Comment by bolt12** [comment]
This tries to tackle this issue: https://github.com/input-output-hk/ouroboros-network/issues/3320 ?

**Comment by coot** [comment]
Yes, it fixes #3320.

**Review by bolt12 — APPROVED** [review]
This is nice :D

**Comment by coot** [comment]
bors merge

**Pull request merged**
