### PR TITLE
Add PBFT CannotLead checks

### PR DESCRIPTION
**Pull request by nc6**
- Check that we are the current delegate of the genesis key
- Check that more blocks than the singing threshold have not been issued.

Addresses #2172

### CODE REVIEW

**Comment by edsko** [comment]
Ah! Also addresses https://github.com/input-output-hk/ouroboros-network/issues/2173 .

**Comment by edsko** [comment]
@nfrisby could you confirm that this means that your tests will work without the invalid blocks check? That would be a great indication that this is doing the right thing.

**Comment by nfrisby** [comment]
> 
> 
> @nfrisby could you confirm that this means that your tests will work without the invalid blocks check? That would be a great indication that this is doing the right thing.

OK. I'll develop a PR on top of this one to simplify the test suite accordingly.

Might not want to block this on that -- not sure how the schedule will proceed.

**Comment by nfrisby** [comment]
Bah. CI failure demonstrates that the answer is "No". I'll increase my priority on it. The particular test that failed is a corner case.

**Comment by nfrisby** [comment]
FYI https://github.com/input-output-hk/ouroboros-network/tree/nfrisby/issue-2172

I've pushed a commit to that branch that extends this PR. It updates the test infrastructure as necessary.

Please cherry-pick it onto this one, if you like it.

The test infrastructure has so far been expecting invalid blocks to be caught by the ChainDB. Since some tests knowingly induce invalid blocks, those tests had been validating such block rejections.

As of this PR, those invalid blocks are never even forged. But we still want to validate the failure to lead. (The fact that we no longer could do so is why the CI failed.) My commit therefore adjusts the test infrastructure to validate `CannotLead`s instead of `BlockRejection`s.

**Comment by edsko** [comment]
@nfrisby that sounds great. I will take a look at this PR now, as well as the commit you refer to, and then hopefully merge.

**Comment by edsko** [comment]
bors merge

**Comment by edsko** [comment]
bors merge

**Comment by edsko** [comment]
bors merge

**Pull request merged**
