### PR TITLE
DONTMERGE: Add consensus to Windows CI

### LINKED ISSUE #1847: Build and test consensus on real Windows in CI
Splitting off from #1082:

> Moreover, as of #1835, CI builds and tests on Windows using Wine (mingw32), which gives us some confidence consensus works on Windows. `cardano-node`, which uses consensus, has been reported to run successfully on Windows.
> 
> I think the only thing left to do is: let CI build and test on Windows (real Windows, _not_ using Wine). @coot has a PR open for this (#1808), when that's merged, we can simply add the consensus tests to it. At that point we'll notice any remaining Windows problems and it will also make sure we don't regress.

### PR DESCRIPTION
**Pull request by mrBliss**
Fixes #1847.

### CODE REVIEW

**Comment by mrBliss** [comment]
Waiting on #1852.

**Comment by mrBliss** [comment]
CI passes, hurray! Adding consensus to CI increases the run-time from ~17 min to ~44 min :slightly_frowning_face:. I think some better caching would improve things:

| Steps                                         | Time       |
|-----------------------------------------------|------------|
| Set up job                                    | 2s         |
| Configure Chocolatey                          | 48s        |
| Install msys2                                 | 3m 14s     |
| Install GHC                                   | 1m 44s     |
| Install Cabal                                 | 2s         |
| Set PATH                                      | 1s         |
| Print versions                                | 1s         |
| cache cabal store                             | 4s         |
| cache buiddir [cache]                         | 1s         |
| cache buiddir [src]                           | 6s         |
| cache builddir [packagedb]                    | 0s         |
| update Hackage index                          | 19s        |
| checkout ouroboros-network repository         | 12s        |
| Use cabal.project.local.windows               | 1s         |
| Win32-network [dependencies]                  | 29s        |
| Win32-network [build]                         | 21s        |
| Win32-network [test]                          | 54s        |
| ntp-client [dependencies]                     | 12s        |
| ntp-client [build]                            | 1s         |
| ntp-client [test]                             | 42s        |
| io-sim-classes [dependencies]                 | 1s         |
| io-sim-classes [build]                        | 6s         |
| io-sim [dependencies]                         | 1s         |
| io-sim [build]                                | 21s        |
| io-sim [test]                                 | 2s         |
| typed-protcols [dependencies]                 | 2s         |
| typed-protocols [build]                       | 4s         |
| typed-protocols-examples [dependencies]       | 1s         |
| typed-protocols-examples [build]              | 14s        |
| typed-protocols-examples [test]               | 4s         |
| network-mux [dependencies]                    | 1s         |
| network-mux [build]                           | 17s        |
| network-mux [test]                            | 52s        |
| ouroboros-network-framework [dependencies]    | 12s        |
| ouroboros-network-framework [build]           | 28s        |
| ourobors-network-framework [test]             | 2m 7s      |
| ouroboros-network [dependencies]              | 14s        |
| ouroboros-network [build]                     | 1m 27s     |
| ouroboros-network [test]                      | 1m 4s      |
| ouroboros-consensus [dependencies]            | **4m 45s** |
| ouroboros-consensus [build]                   | 2m 52s     |
| ouroboros-consensus [test-consensus]          | 8s         |
| ouroboros-consensus [test-storage]            | 6s         |
| ouroboros-consensus-test-infra [dependencies] | 6s         |
| ouroboros-consensus-test-infra [build]        | 38s        |
| ouroboros-consensus-test-infra [test]         | 3s         |
| ouroboros-consensus-mock [dependencies]       | 2s         |
| ouroboros-consensus-mock [build]              | 34s        |
| ouroboros-consensus-mock [test]               | 1m 34s     |
| ouroboros-consensus-byronspec [dependencies]  | **8m 25s** |
| ouroboros-consensus-byronspec [build]         | 16s        |
| ouroboros-consensus-byron [dependencies]      | 36s        |
| ouroboros-consensus-byron [build]             | 47s        |
| ouroboros-consensus-byron [test]              | 3m 53s     |
| ouroboros-consensus-byron [db-analyser]       | 2s         |
| ouroboros-consensus-byron [db-converter]      | 2s         |
| ouroboros-consensus-shelley [dependencies]    | 1m 19s     |
| ouroboros-consensus-shelley [build]           | 44s        |
| ouroboros-consensus-shelley [test]            | 34s        |
| ouroboros-consensus-cardano [dependencies]    | 2s         |
| ouroboros-consensus-cardano [build]           | 9s         |
| Post checkout ouroboros-network repository    | 2s         |
| Post cache builddir [packagedb]               | 0s         |
| Post cache buiddir [src]                      | 0s         |
| Post cache buiddir [cache]                    | 0s         |
| Post cache cabal store                        | 0s         |
| Complete job                                  | 0s         |

I would expect that "Configure Chocolatey", "Install msys2", and "Install GHC" can be cached.

Moreover, I have highlighted some steps that really should benefit from caching. We're building all our `source-repository-package` dependencies from scratch each time, which is a waste.

Finally, for all the four `Post cache ...` steps, I see:
```
Cache hit occurred on the primary key X, not saving cache.
```
Is that correct? It seems like it is not caching things.

**Comment by Jasagredo** [comment]
I think this one is no longer applicable? CC: @coot

**Comment by coot** [comment]
Yes, closing.

**Pull request closed without merging**
