### PR TITLE
Subscription worker - state mangment

### PR DESCRIPTION
**Pull request by coot**
This is redesign of subscription worker to add state (abstract in this PR).  It is done in the style of `Server.Socket`.

It relies on PR #912 .

### CODE REVIEW

**Comment by karknu** [comment]
What what is the usecase for `ba66704`? What kind of data will we store in a ~connection table~ that doesn't have a `SockAddr`.?

**Comment by coot** [comment]
@karknu I wanted to make `Subscription.Worker` independent of `Network.Socket` types. By being polymorphic, we say we only can do stuff which are allowed by constraints. In this case it's just `Ord addr` to use it as keys of a `Map` in connection table.

**Comment by karknu** [comment]
Dang, too late. :)

**Comment by coot** [comment]
No worries @karknu , I'll submit another PR to fix that.

**Pull request merged**
