### PR TITLE
Updated versions of github actions

### PR DESCRIPTION
**Pull request by coot**
- `actions/checkout@v3`
- `actions/cache@v3`
- using `ubuntu-latest` instead of the `ubuntu-20.04`
- introduced dependabot for GitHub Actions.

### CODE REVIEW

**Comment by coot** [comment]
I noticed that the `actions/cache@v2` for `dist-newstyle` constistently fails with
```
C:\Windows\System32\tar.exe -z -xf D:/a/_temp/78411900-0fac-4820-a41b-10aca31c78c5/cache.tgz -P -C D:/a/ouroboros-network/ouroboros-network
dist-newstyle/src/Win32-net_-e9415802910225c6/.git/objects/pack/pack-454b815897eaaeae85e9b284d6e897c844950cb2.idx: Can't unlink already-existing object
dist-newstyle/src/Win32-net_-e9415802910225c6/.git/objects/pack/pack-454b815897eaaeae85e9b284d6e897c844950cb2.pack: Can't unlink already-existing object
...
dist-newstyle/src/cardano-c_-e62f2aeae532ef4f/.git/objects/pack/pack-8f2a94d9aae12bccabd3b5e4f36d249c3a861bdc.pack: Can't unlink already-existing object
tar.exe: Error exit delayed from previous errors.
Warning: Tar failed with error: The process 'C:\Windows\System32\tar.exe' failed with exit code 1
```
Let's see if using `actions/cache@v3` will fix this error.

**Review by bolt12 — APPROVED** [review]

**Review by amesgen — APPROVED** [review]
We could also configure dependabot (by adding a file to this repo) to automatically get PRs updating these versions: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

**Comment by coot** [comment]
@amesgen good idea, I copied the configuration you pointed to.

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
bors cancel

**Comment by coot** [comment]
bors merge

**Pull request merged**
