### PR TITLE
fix #821: testBlockchainTime was creating on extra slot

### LINKED ISSUE #821: Protocol testing: respect `NumSlots` in `testBlockchainTime`
As of `63bd94f4`, given `NumSlots n`, `testBlockchainTime` ticks `n` times. But it begins with `SlotNo 0`, so it ends in `SlotNo n`. Thus there are `n+1` slots. (`SlotNo` is defined to be 0-based.)

This Issue is to resolve that incoherency.

Current plan: try initializing the `TVar` to `Nothing` in `testBlockchainTime`.

### PR DESCRIPTION
**Pull request by nfrisby**
The patch is simple and does what we discussed on #821. But it's a Draft PR at the moment because the `Praos` test consumes all my machine's memory.

### CODE REVIEW

**Comment by nfrisby** [comment]
The source of the crash:

https://github.com/input-output-hk/ouroboros-network/blob/71c9da7b096cecda160ad81a9564e2e7c7aa4139/ouroboros-consensus/src/Ouroboros/Consensus/Protocol/Praos.hs#L309-L313

That function is being called with `SlotNo 0`, and so the subtraction underflows. (The resulting huge `Word64` causes lots of allocation when it reaches elsewhere in this module.)

I'm unfamiliar with this territory, but that `- 1` seems quite suspicious, considering `SlotNo` is defined to be 0-indexed.

**Comment by mrBliss** [comment]
> The source of the crash:
> 
> https://github.com/input-output-hk/ouroboros-network/blob/71c9da7b096cecda160ad81a9564e2e7c7aa4139/ouroboros-consensus/src/Ouroboros/Consensus/Protocol/Praos.hs#L309-L313
> 
> That function is being called with `SlotNo 0`, and so the subtraction underflows. (The resulting huge `Word64` causes lots of allocation when it reaches elsewhere in this module.)
> 
> I'm unfamiliar with this territory, but that `- 1` seems quite suspicious, considering `SlotNo` is defined to be 0-indexed.
> 
> @mrBliss, @dcoutts: Who should I ping for an opinion on this? The summary of my patch that causes this line to cause a crash is: running tests with `NumSlots n` was actually running with `n + 1` slots, `[0 .. n]`. My patch changes that so it's instead a "before `SlotNo 0`" initialization phase in which only "test initialization" code should run and then `n` slots, `[0 .. n - 1]`.

The `-1` is indeed strange since both `SlotNo` and `EpochNo` are 0-indexed. I would expect
```haskell
slotEpoch PraosNodeConfig{..} s = EpochNo $ div (unSlotNo s) praosSlotsPerEpoch
..
epochStart PraosNodeConfig{..} e = SlotNo $ (unEpochNo e) * praosSlotsPerEpoch
```

Even better would be to reuse`EpochInfo`: https://github.com/input-output-hk/ouroboros-network/blob/bcab58a2faa5edafd9c3ecd5e7baaa94d1845d96/ouroboros-consensus/src/Ouroboros/Storage/EpochInfo/Impl.hs#L46 (and reuse the existing `EpochNo` type too).

We should do that as a separate PR. Would you mind doing that first? Since this PR is kind of blocked on this :slightly_smiling_face:

**Comment by nfrisby** [comment]
> We should do that as a separate PR. Would you mind doing that first? Since this PR is kind of blocked on this

I opened #835 for this.

**Comment by nfrisby** [comment]
An improvement occurred to me while I was refactoring the general test setup for another PR. I've rebased with those changes.

I also rebased atop the pending #835, to avoid the memory exhaustion bug.

This rebase also fixes a bug in the prior commit: the thread delay should now happen after incrementing the `TVar`, not before it.

**Comment by nfrisby** [comment]
Thanks for merging #835; I've rebased this onto the latest master.

**Pull request merged**
