### PR TITLE
Add the cut_body_after field to bors.toml

### PR DESCRIPTION
**Pull request by dnadales**
... so that the PR checklist is ignored in the merge commit message.

# Checklist

- Branch
    - [ ] Commit sequence broadly makes sense
    - [ ] Commits have useful messages
    - [ ] New tests are added if needed and existing tests are updated
    - [ ] If this branch changes Consensus and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../ouroboros-consensus/docs/interface-CHANGELOG.md)
    - [ ] If this branch changes Network and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../docs/interface-CHANGELOG.md)
    - [ ] If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.
- Pull Request
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by nfrisby** [comment]
bors try

**Comment by nfrisby** [comment]
I was hoping that would cause bors to create a consequence-less merge commit, but I guess it doesn't 🤔

**Comment by dnadales** [comment]
I'm thinking we might want to merge this without bors, in case it uses the `bors.toml` before this change :grimacing:

**Review by coot — APPROVED** [review]
LGTM

**Comment by coot** [comment]
Merged without bors, before start of the week.

**Pull request merged**
