### PR TITLE
Handshake refactoring

### PR DESCRIPTION
**Pull request by coot**
Remove dependently typed version data from Handshake.

### CODE REVIEW

**Review by karknu — APPROVED** [review]
LGTM.
Please squash all the "update X" commits so that we don't have 10 commits where ouroboros-network is unbuildable. It makes it hard to bisect.

**Comment by mrBliss** [comment]
> Please squash all the "update X" commits so that we don't have 10 commits where ouroboros-network is unbuildable. It makes it hard to bisect.

I agree with @karknu :slightly_smiling_face:

**Comment by coot** [comment]
All the commits are squashed.

**Comment by coot** [comment]
Windows failure is unrelated, I am working on it in #2710.

bors merge

**Pull request merged**
