### PR TITLE
Use `git show` instead in consensus-changelog check

### PR DESCRIPTION
**Pull request by Jasagredo**

### CODE REVIEW

**Comment by Jasagredo** [comment]
> https://github.com/input-output-hk/ouroboros-network/actions/runs/4134784462/jobs/7146355313 is showing git failures in the consistency check

I don't see those? unless you rerun it and they are gone now

**Comment by jorisdral** [comment]
> > https://github.com/input-output-hk/ouroboros-network/actions/runs/4134784462/jobs/7146355313 is showing git failures in the consistency check
> 
> I don't see those? unless you rerun it and they are gone now

I see  `fatal: ambiguous argument 'HEAD^': unknown revision or path not in the working tree.` in the `Check changelog consistency` check, so I don't think the script is doing what it is supposed to

**Comment by Jasagredo** [comment]
> > > https://github.com/input-output-hk/ouroboros-network/actions/runs/4134784462/jobs/7146355313 is showing git failures in the consistency check
> > 
> > 
> > I don't see those? unless you rerun it and they are gone now
> 
> I see `fatal: ambiguous argument 'HEAD^': unknown revision or path not in the working tree.` in the `Check changelog consistency` step, so I don't think the script is doing what it is supposed to, even though the step does not fail

Lol what is going on, this is on my machine:
```
❯ git diff HEAD^ HEAD ouroboros-consensus-cardano/ouroboros-consensus-cardano.cabal | grep "+version"
+version:  
```

**Comment by amesgen** [comment]
Probably due to the sparse checkout:

> Only a single commit is fetched by default, for the ref/SHA that triggered the workflow. Set `fetch-depth: 0` to fetch all history for all branches and tags.

https://github.com/actions/checkout/#checkout-v3

**Comment by Jasagredo** [comment]
Now this should finally work. cc @amesgen @jorisdral

**Review by jorisdral — APPROVED** [review]

**Pull request merged**
