### PR TITLE
Export constructors for TraceKeepAliveClient

### PR DESCRIPTION
**Pull request by karknu**

### CODE REVIEW

**Comment by coot** [comment]
I think they should also be exported from `Ouroboros.Network.NodeToNode` module.

**Comment by karknu** [comment]
> I think they should also be exported from `Ouroboros.Network.NodeToNode` module.

Why?
`Ouroboros.Network.NodeToNode` doesn't currently import `Ouroboros.Network.KeepAlive` and other "application level" tracers are not exported such as TraceTxSubmissionInbound, TraceTxSubmissionOutBound and blockfetch.

**Comment by coot** [comment]
ok, let's leave this as is.

**Review by coot — APPROVED** [review]
LGTM

**Pull request merged**
