### PR TITLE
Enable NoThunk tests by adding checkTVarInvariant option for building 'strict-stm'

### LINKED ISSUE #3001: Check the `NoThunks` invariant during a nightly CI test
If you set the following flag and run the test suite, most `TVar`s -- including all critical ones, unless we have a bug -- will check their contents for thunks via the `nothunks` library whenever they're updated.

```
$ cat cabal.project.local
package io-classes
  flags: +checktvarinvariant
```

This flag makes the tests run quite slow, so it's something we had been doing incrementally. But I, for example, haven't done it since taking over lead for two months! So adding it to some CI (nightly, but perhaps even just weekly) would be much safer.

Edit: `io-sim-classes` was renamed `io-classes` on 2021 July 8.

### PR DESCRIPTION
**Pull request by yogeshsajanikar**
# Description

- Add a flag checkTVarInvariant to ./nix/ouroboros-network.nix
- haskellPackagesWithTVarCheck points to strict-stm package with "checktvarinvariant" flag enabled.
- nix-build -A tvar-invariant-checks.tests runs the tests with "checktvarinvariant" flag turned on

This PR allows adding an ability to run strict tvar invariant check in strict-stm. This enables `nothunk` tests, and also simplifies running it. The github actions will be added once existing nothunk failures (#4006 ) are fixed.

E.g. to run a single test

``` bash
nix-build -A tvar-invariant-checks.tests.ouroboros-consensus-test.test-storage
```
To enter nix-shell with `checkTVarInvariant` enabled

```bash
nix-shell --arg checkTVarInvariant true
```
And then in the nix shell, it is possible to use `cabal` to run the tests for checking no thunks.

E.g.
```bash
cabal run test-storage
```

fixes #3001 

# Checklist
- Branch
    - [ ] Commit sequence broadly makes sense
    - [ ] Commits have useful messages
    - [ ] New tests are added if needed and existing tests are updated
    - [ ] If this branch changes Consensus and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../ouroboros-consensus/docs/interface-CHANGELOG.md)
    - [ ] If this branch changes Network and has any consequences for downstream repositories or end users, said changes must be documented in [`interface-CHANGELOG.md`](../docs/interface-CHANGELOG.md)
    - [ ] If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.
- Pull Request
    - [x] Self-reviewed the diff
    - [ ] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [ ] Reviewer requested

### CODE REVIEW

**Review by amesgen — APPROVED** [review]
LGTM, only circumstantial remarks:

 - Update the PR title
 - Update the PR description to mention the new shell option and how to use it.
 - Squash all commits

**Comment by yogeshsajanikar** [comment]
bors +

**Comment by yogeshsajanikar** [comment]
bors cancel

**Comment by coot** [comment]
I forgot to update `bors.toml` file in #3986, so bors will timeout.  Let's cancel it and restart.

bors cancel

**Comment by coot** [comment]
@yogeshsajanikar you need to rebase it once #3986 is merged.

**Pull request merged**
