### PR TITLE
Encoding & Decoding of ControlMessages

### PR DESCRIPTION
**Pull request by coot**
I changed the encoding of `MsgInitReq` to use lists, and I added generators to test that we can decode all versions that we accept.

### CODE REVIEW

**Comment by karknu** [comment]
Overall I really like the changes, especially the generator for control message.

I still prefer the wire format in my branch, i.e a CBOR map instead of a CBOR list of lists.

**Comment by coot** [comment]
I think it's possible. It should only require to change `encodeVersions` function (and adjusting the decoder).

**Comment by coot** [comment]
An after thought, here we can plug `Serialise` instance of `Version`, in the other case that will not be possible. Which means that when adding new `Version` one will need not to forget to update the other place. This will not be catched by `-Werror` on CI, since likely there's `_` in relevant  patter match to catch all cases which we don't know about. For that reason I actually prefer what's here.

**Comment by karknu** [comment]
The usage of `VersionNumber` in my branch means that that case is caught by the CI.

**Pull request merged**
