### PR TITLE
Make ImmDB `Iterator`/`IteratorResult` functors

### PR DESCRIPTION
**Pull request by edsko**

### CODE REVIEW

**Comment by edsko** [comment]
Hmmmmmmmmmmmmmmmmmmmmmmmm. Now that I am actually using this..... What about the iterator IDs...? :thinking: Even ignroing these `Functor` instances, I want to be able to write something like

```haskell
-- | Stream blocks after the given point
--
-- See also 'streamBlobsAfter'.
streamBlocksAfter :: forall m blk. (MonadCatch m, StandardHash blk, Typeable blk)
                  => ImmDB m blk
                  -> Point blk -- ^ Exclusive lower bound
                  -> m (Iterator (HeaderHash blk) m blk)
streamBlocksAfter db low = wrap <$> streamBlobsAfter db low
  where
    wrap :: Iterator (HeaderHash blk) m Strict.ByteString
         -> Iterator (HeaderHash blk) m blk
    wrap itr = Iterator {
          iteratorNext  = ...
        , iteratorClose = iteratorClose itr
        , iteratorID    = iteratorID    itr
        }
```

but again, that would result in different iterators with the same `ID` and hence reported as equal... 

Not entirely sure what to do with that. Maybe the `Eq` instance should go?

**Comment by mrBliss** [comment]
The main reason for having the `Ord` instance (which we would lose if we remove the `Eq` instance) and in fact `iteratorID` is that we need to store iterators in a map (see `KnownIters` in the q-s-m tests).

I would be happy to drop these ugly `iteratorID`s (which would make the path clear for this PR) if we have a better solution that allows us to store them in a map.

Another idea: if we somehow only expose the `iteratorID`s to the testsuite and move the `Eq` and `Ord` instances to the testsuite as well, we don't need to care that an `fmap`ped iterator shares its `iteratorID` with another iterator. We would only have to be careful in the testsuite.

**Comment by edsko** [comment]
Explored the option of removing the `Eq`/`Ord` instances. This has a number of consequences though:

1. The `knownIters` in the model now need to be map from `IteratorID` to mock iterators, rather from iterators to iterators.
2. We need some generalizations of the `RefEnv`, and some infrastructure for mapping over references (from `Reference (Iterator ..) r` to `Reference IteratorID r`
3. This then leaves us unable to _close_ all iterators (since we'd only have their IDs), so we'd have to extend the model or fix #328 first.

None of this is impossible but also would get us no closer to a working chain DB. Instead changed iterator IDs to

```haskell
-- | ID of an iterator that is not derived from another iterator
newtype BaseIteratorID = MkBaseIteratorID Int
  deriving (Show, Eq, Ord, Generic, Enum)

-- | A unique identifier for an iterator.
data IteratorID = BaseIteratorID BaseIteratorID | DerivedIteratorID IteratorID
  deriving (Show, Eq, Ord, Generic)
```

to avoid the problem mentioned above.

**Comment by avieth** [comment]
Would it be feasible to use a different iterator type for mock? Then we can put the ID in that one, and leave it out in the real one.

I have defined my own `Iterator` type for the Byron proxy DB abstraction because I didn't want the iterator ID (I'd have to come up with my own, which just seemed wrong).

**Comment by edsko** [comment]
> Would it be feasible to use a different iterator type for mock? Then we can put the ID in that one, and leave it out in the real one.

No, the q-s-m tests map the real iterators to mock iterators (same type, actually); it's the _from_ iterator (the real one) that we really need to be able to have an ID for.

> I have defined my own Iterator type for the Byron proxy DB abstraction because I didn't want the iterator ID (I'd have to come up with my own, which just seemed wrong).

I don't get this. Why would you have to come up with your own IDs?

**Comment by avieth** [comment]
> I don't get this. Why would you have to come up with your own IDs?

Because I want `none :: Applicative m => Iterator m t`, `one :: Applicative t => t -> Iterator m t` etc.

**Comment by avieth** [comment]
> No, the q-s-m tests map the real iterators to mock iterators (same type, actually); it's the from iterator (the real one) that we really need to be able to have an ID for.

But the ID is only used for testing/simulation or similar yes?

**Comment by edsko** [comment]
> But the ID is only used for testing/simulation or similar yes?

Currently, yes, that's the case. Not sure that will remain to be the case; possibly, though not totally sure (compare `readerId` in `ReaderState`, I suppose).

**Comment by edsko** [comment]
(Merged since this discussion is somewhat orthogonal to this PR.)

**Comment by edsko** [comment]
We could remove the `iteratorID` part but it would require various changes to the tests (not impossible, but a little time consuming), and I'm not _entirely_ sure that we should. It's occasionally useful of iterators have an `Eq`/`Ord` instance (another data point: `Eq` instance for `Handle` from `System.IO`).

I agree that it's not optimal though.. :/

**Comment by edsko** [comment]
I guess we could easily move your `Eq`-less and `iteratorID`-less version to the (chain) DB itself though; that's easy enough to do.

**Pull request merged**
