### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by coot**
- io-sim-por: delete terminated threads
- removed TipSample protocol
- ouroboros-network: renamed ouroboros-protocol-tests component
- typed-protocols: fixed a typo
- block-fetch: typos
- ouroboros-network:test Fix a typo
- ouroboros-network-framework: align the code

### CODE REVIEW

**Review by bolt12 — APPROVED** [review]

**Comment by bolt12** [comment]
CI error, seems like an import that no longer exists

**Comment by coot** [comment]
bors merge

**Comment by coot** [comment]
Requires #3474 (rebased on top of it).

**Review by bolt12 — APPROVED** [review]

**Comment by coot** [comment]
bors halt

**Comment by coot** [comment]
bors merge

**Pull request merged**
