### PR TITLE
update ledger

### PR DESCRIPTION
**Pull request by goolord**
depends on / includes changes from https://github.com/input-output-hk/ouroboros-network/pull/3356
but includes newer changes from the ledger

### CODE REVIEW

**Review by nfrisby — CHANGES_REQUESTED** [review]
@goolord Please remove the merge commit in order to linearize the commit history -- we avoid merge commits in our feature branches unless they would be extremely costly to eliminate. Thanks!

Edit: Actually, now that I'm looking more carefully, I think I'm just asking for your to "rebase" your changes on to the current `ouroboros-network` `master` branch, since Clarke's PR merged a bit a go.

**Comment by goolord** [comment]
squash and merge is an option

**Comment by nfrisby** [comment]
@goolord We use `bors` to merge. I haven't seen it "squash and merge". Do you know how to do that via `bors`? Thanks.

**Comment by goolord** [comment]
ah, i was under the wrong impression about bors. regardless, the commits are cleaned up

**Review by nfrisby — APPROVED** [review]
Approved. Thanks!

**Comment by goolord** [comment]
bors merge

**Pull request merged**
