### PR TITLE
Handle multiple blocks with the same SlotNo in chain-like data types

### LINKED ISSUE #816: Handle multiple blocks with the same SlotNo in Chain/ChainFragment/AnchoredFragment
So far we have always assumed that the blocks in a `Chain`/`ChainFragment`/`AnchoredFragment` have strictly increasing `SlotNo`s. We use this fact in the implementation, e.g., splitting the underlying finger-tree based on the `SlotNo`, looking up by `SlotNo` (and returning `Maybe blk`) etc.

However, an EBB has the same `SlotNo` as the regular block after it, so our assumption no longer holds and the functionality on chain-like types no longer works correctly :angry:. (This was discovered when trying to sync with mainnet + using `AnchoredFragment.successorBlock` on the resulting chain).

Possible plan:
- Let's not change our assumption from 0-1 blocks with the same `SlotNo` to 0-2, but to 0-n. This is more general, less error-prone, and will be easier to test.
- We no longer export slot-based functionality from `Chain`/`ChainFragment`/`AnchoredFragment`, e.g., `slotOnChainFragment`, `splitBeforeSlot`, `lookupBySlot`, etc. This functionality is not used anywhere except in the modules themselves to implement point-based variants of these functions.
- We generalise the slot-based functions (or do this directly in the point-based variants) to handle the fact that there might be more than one block with the same `SlotNo` and adapt the point-based functions accordingly. E.g., try all blocks with the same `SlotNo` until one is found with the correct hash. This carries an extra cost, but it is bounded by the number of blocks with the same `SlotNo`, which will be at most 2 in practice.

This means that the API is shrunk (slot-based functions gone), but the existing point-based functionality is unchanged, except for the fact that it now correctly deals with multiple blocks with the same `SlotNo`.

### PR DESCRIPTION
**Pull request by mrBliss**
Closes #816: don't assume that the blocks in a
`Chain`/`ChainFragment`/`AnchoredFragment` have strictly increasing `SlotNo`s,
as EBBs have the same `SlotNo` as the block after them.

* Add gap size 0 in the chain generators so that blocks with the same `SlotNo`
  as the one before it are generated.
* Remove slot-based functionality from the API or hide it. For example, remove
  `ChainFragment.splitAfterSlot`, since it would have to return a list of
  splits. Hide `ChainFragment.lookupBySlot` and change its return type from
  `Maybe block` to `[block]`.
* Adapt the point-based variants accordingly: `ChainFragment.splitAfterPoint`
  will try multiple splits until the block with the right hash is found. This
  has an additional cost of *O(s)* where *s* is the number of blocks with the
  same `SlotNo`.

### CODE REVIEW

**Comment by mrBliss** [comment]
Just force-pushed to include the typo fix @coot noticed and wanted to fix in #819.

**Comment by mrBliss** [comment]
I'm fixing the test failures.

**Comment by avieth** [comment]
>I'm fixing the test failures.

I had a quick look. The failing case is IMO implemented in a pretty sloppy way: exceptions in the consumer and producer threads are squelched. `wait`ing on both of them before the final `takeTMVar done` reveals the assertion failure at `src/Ouroboros/Network/MockChain/ProducerState.hs:201:11`

**Comment by mrBliss** [comment]
> > I'm fixing the test failures.
> 
> I had a quick look. The failing case is IMO implemented in a pretty sloppy way: exceptions in the consumer and producer threads are squelched. `wait`ing on both of them before the final `takeTMVar done` reveals the assertion failure at `src/Ouroboros/Network/MockChain/ProducerState.hs:201:11`

I don't have time to fix this today. Feel free to fix it yourself, push it to this PR's branch, and merge it 🙂

**Comment by avieth** [comment]
A related issue: EBBs have the same `BlockNo`/difficulty as their parent. Do the chain datatypes deal with this?

**Comment by avieth** [comment]
@dcoutts note the final commit, which somehow fixes the `blockGenerator invariant IO` test that has me completely baffled.

**Comment by mrBliss** [comment]
> A related issue: EBBs have the same `BlockNo`/difficulty as their parent. Do the chain datatypes deal with this?

I think we need your commit: https://github.com/input-output-hk/ouroboros-network/commit/a3d6160410fbc5bbb435e0d9b6dbbf369bcc8188 (I have always tested the byron-proxy with that branch).

**Pull request merged**
