### PR TITLE
CHaP + strict-containers -> cardano-strict-containers

### PR DESCRIPTION
**Pull request by angerman**
This is part of the work towards https://github.com/input-output-hk/cardano-node/pull/4608

In this PR:
- [x] Adapt to `strict-containers` -> `cardano-strict-containers` change.
- [x] Base on CHaP where possible.

### CODE REVIEW

**Comment by angerman** [comment]
We should also be able to bump to a proper 1.1.1 release from https://github.com/input-output-hk/cardano-ledger/commits/release/1.1.x, later today. At which point there would be no `source-repository-packages` left in the `cabal.project`!

**Review by coot — APPROVED** [review]
LGTM

**Review by dnadales — APPROVED** [review]
LGTM

**Comment by angerman** [comment]
Whoo Hoo, LFG!

**Comment by angerman** [comment]
bors merge

**Comment by amesgen** [comment]
bors retry

**Pull request merged**
