### PR TITLE
Fixed images not rendering

### PR DESCRIPTION
**Pull request by bolt12**
Tackling issue #2878 .

### CODE REVIEW

**Review by coot — APPROVED** [review]
LGTM

**Comment by bolt12** [comment]
How to proceed in order to update the actual documents that are hosted on Hydra?

**Comment by coot** [comment]
That will be done by hydra itself, once it's merged.

**Comment by bolt12** [comment]
bors merge

**Review by dcoutts — APPROVED** [review]
LGTM

**Comment by dcoutts** [comment]
bors merge

**Comment by bolt12** [comment]
bors merge

**Pull request merged**
