### PR TITLE
Add cardano-client to the required CI builds

### PR DESCRIPTION
**Pull request by MarcFontaine**
By default CI picks up all test-suites as required build.
There are no reasonable tests for the cardano-client library at the moment.
This add a dummy test-suite to still make it a required build.

### CODE REVIEW

**Comment by coot** [comment]
@MarcFontaine instead of adding a dummy test suite (I don't think we will have one soon), I am quite sure there's a way modify `release.nix`.  Maybe by adding a job to `jobs`. You can ask deveops for help.

**Comment by MarcFontaine** [comment]
That is also an option. I looked at `release.nix` there is a line where I could add it.
I wanted to avoid to make `cardano-client` a special case in CI and
make nix more complicated.
Next time the nix-files need to be changed the extra requirement may get lost.

**Comment by MarcFontaine** [comment]
https://github.com/input-output-hk/ouroboros-network/pull/2136

**Comment by MarcFontaine** [comment]
fixed in https://github.com/input-output-hk/ouroboros-network/pull/2155

**Pull request closed without merging**
