### PR TITLE
p2p peer selection

### PR DESCRIPTION
**Pull request by dcoutts**
Work in progress for #1306. So far we have:

* local root peers
* public root peers
* peer gossip
* forgetting peers
* targets for root peers and known peers
* QC tests covering local roots and gossip (but not public roots)

### CODE REVIEW

**Comment by dcoutts** [comment]
Now also have: establ

**Comment by avieth** [comment]
Ready to merge this? The hydra failing is just `-Werror` for `unused-top-binds`.

**Pull request merged**
