### PR TITLE
Updated nix environment

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Comment by avieth** [comment]
Is this still relevant?

**Comment by coot** [comment]
I am just looking into that ...

**Comment by edsko** [comment]
This was needed by #139 but will likely be superseded by a different PR from @coot .

**Comment by coot** [comment]
@edsko I updated this PR. `ouroboros-consensus` built locally without any errors, so it also should run on CI.

**Comment by edsko** [comment]
Thanks!

**Pull request merged**
