### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by eyeinsky**
- Of cause => Of course
- EOL spaces removed

# Description

_description of the pull request, if it fixes a particular issue it should link the PR to a particular issue, see [ref](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=)_

# Checklist

- Branch
    - [-] Updated changelog files.
    - [X] Commit sequence broadly makes sense
    - [X] Commits have useful messages
    - [X] The documentation has been properly updated
    - [-] New tests are added if needed and existing tests are updated
    - [X] If serialization changes, user-facing consequences (e.g. replay from genesis) are confirmed to be intentional.
- Pull Request
    - [X] Self-reviewed the diff
    - [X] Useful pull request description at least containing the following information:
      - What does this PR change?
      - Why these changes were needed?
      - How does this affect downstream repositories and/or end-users?
      - Which ticket does this PR close (if any)? If it does, is it [linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
    - [X] Reviewer requested

### CODE REVIEW

**Comment by eyeinsky** [comment]
Got it, and done!

**Review by bolt12 — APPROVED** [review]

**Comment by eyeinsky** [comment]
(Found one more and force-pushed it: arguemts => arguments)

**Comment by eyeinsky** [comment]
One more: communicate communicate => communicate

**Comment by bolt12** [comment]
Alright! Keep it up 😄 Thank you!

**Review by coot — APPROVED** [review]
LGTM, thanks for your contribution.

**Comment by coot** [comment]
@eyeinsky could you squash the commits and rebase them on top of master?

**Comment by coot** [comment]
Closing it in favour of #4659, thank you @eyeinsky.

**Comment by eyeinsky** [comment]
@coot Sorry, somehow missed this, thanks for making the other PR! :)

**Pull request closed without merging**
